# Generated by Django 6.0.6 on 2026-06-11 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic_type', models.CharField(choices=[('KEYWORD', 'Keyword'), ('CATEGORY', 'Category'), ('TAG', 'Tag')], help_text='Category of Logic', max_length=20, verbose_name='Logic Type')),
                ('value', models.CharField(help_text='Logic Value', max_length=512, verbose_name='Value')),
                ('parent', models.ForeignKey(blank=True, help_text='What category does this tag belog to', limit_choices_to={'logic_type': 'CATEGORY'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='website.logic', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Logic',
                'verbose_name_plural': 'Logic',
                'db_table': 'logic',
                'ordering': ['logic_type'],
                'unique_together': {('value', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Site', max_length=256, verbose_name='Name')),
                ('url', models.URLField(help_text='Top level URL of the Site', verbose_name='Site URL')),
                ('rss_feed', models.URLField(help_text='The URL of the Feed', verbose_name='Feed URL')),
                ('bluesky', models.CharField(help_text='Bluesky Handle', max_length=256, verbose_name='Bluesky')),
                ('modifier', models.FloatField(default=2, help_text='Rank Modifier', verbose_name='Modifier Value')),
                ('last_article', models.IntegerField(default=0, help_text='Days since last article', verbose_name='Last Article')),
                ('hidden', models.BooleanField(default=False, help_text='Is this site hidden?', verbose_name='Site Hidden')),
                ('rss_error', models.BooleanField(default=False, help_text='Has this site had RSS issues?', verbose_name='RSS Error')),
                ('description', models.TextField(help_text='Explanation of the site', max_length=2000, verbose_name='Site Description')),
                ('category', models.ForeignKey(help_text='Select a category for this site', limit_choices_to={'logic_type': 'CATEGORY'}, on_delete=django.db.models.deletion.CASCADE, related_name='site_category', to='website.logic', verbose_name='Category')),
                ('tags', models.ManyToManyField(help_text='Select tags for this site', limit_choices_to={'logic_type': 'TAG'}, related_name='site_tag', to='website.logic', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Sites',
                'verbose_name_plural': 'Sites',
                'db_table': 'sites',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['hidden'], name='hidden_site_idx'), models.Index(fields=['url'], name='url_idx')],
                'constraints': [models.UniqueConstraint(fields=('url',), name='unique_site_url')],
            },
        ),
    ]
