# Generated by Django 6.0.6 on 2026-06-11 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='site_type',
            field=models.ForeignKey(help_text='Select a type for this site', limit_choices_to={'logic_type': 'SITE_TYPE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_type', to='website.logic', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='logic',
            name='logic_type',
            field=models.CharField(choices=[('KEYWORD', 'Keyword'), ('CATEGORY', 'Category'), ('TAG', 'Tag'), ('SITE_TYPE', 'Type')], help_text='Category of Logic', max_length=20, verbose_name='Logic Type'),
        ),
    ]
