# Generated by Django 6.0.6 on 2026-06-11 11:48

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sites_site_type_alter_logic_logic_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Article Title')),
                ('url', models.URLField(verbose_name='Article URL')),
                ('image_url', models.CharField(max_length=512, verbose_name='Image Reference')),
                ('published', models.DateField(blank=True, help_text='The date the article was published', null=True, verbose_name='Published Date')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date the article was created in the site', null=True, verbose_name='Created Date')),
                ('run_id', models.IntegerField(default=0, help_text='The id of the run that this article was part of', verbose_name='Run Id')),
                ('boost', models.FloatField(default=0, help_text='Boosts the article artificially', verbose_name='Boost Count')),
                ('clicks', models.FloatField(default=0, help_text='Count of link clicks', verbose_name='Click Count')),
                ('modifier', models.FloatField(default=1, verbose_name='Modifier Score')),
                ('rank', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('clicks'), '+', models.F('boost')), '*', models.F('modifier')), output_field=models.IntegerField(default=0, help_text='Rank in the feed', verbose_name='Rank Score'))),
                ('hidden', models.BooleanField(default=False, help_text='The article is hidden', verbose_name='Article Hidden')),
                ('site_hide', models.BooleanField(default=False, help_text='The parent site is hidden', verbose_name='Site Hidden')),
                ('bluesky', models.BooleanField(default=False, help_text='The article has been posted to Bluesky', verbose_name='Article Posted to Bluesky')),
            ],
            options={
                'verbose_name': 'Articles',
                'verbose_name_plural': 'Articles',
                'db_table': 'articles',
                'ordering': ['created'],
            },
        ),
        migrations.RemoveIndex(
            model_name='sites',
            name='hidden_site_idx',
        ),
        migrations.RemoveIndex(
            model_name='sites',
            name='url_idx',
        ),
        migrations.AddField(
            model_name='articles',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sites'),
        ),
        migrations.AddConstraint(
            model_name='articles',
            constraint=models.UniqueConstraint(fields=('url',), name='unique_url'),
        ),
    ]
