# Generated by Django 6.0.6 on 2026-06-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_articles_remove_sites_hidden_site_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='bluesky',
            field=models.CharField(help_text='Bluesky Handle incl @', max_length=256, verbose_name='Bluesky'),
        ),
    ]
