# Generated by Django 6.0.6 on 2026-06-12 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_sites_bluesky'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='rss_error',
        ),
    ]
