# Generated by Django 6.0.6 on 2026-06-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_sites_rss_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='batch_num',
            field=models.IntegerField(default=0, help_text='Ingest Batch Number', verbose_name='Batch Number'),
        ),
    ]
