# Generated by Django 6.0.6 on 2026-06-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_sites_batch_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('INGEST_COMPLETE', 'Ingest Complete'), ('INGEST_ERROR', 'Ingest Error'), ('INGEST_RUN_ID', 'Ingest Run Number')], help_text='Category of Log', max_length=20, verbose_name='Log Type')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date the log occured', null=True, verbose_name='Created Date')),
                ('value', models.TextField(help_text='Value of the log', max_length=9000, verbose_name='Logging Output')),
            ],
            options={
                'verbose_name': 'Logging',
                'verbose_name_plural': 'Logging',
                'db_table': 'logging',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='sites',
            name='load_error',
            field=models.BooleanField(default=False, help_text='Has this site had a load error?', verbose_name='Load Error'),
        ),
    ]
