# Generated by Django 6.0.6 on 2026-07-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_logging_log_type_logging_unique_ingest_run_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='log_type',
            field=models.CharField(choices=[('INGEST_COMPLETE', 'Ingest Complete'), ('INGEST_ERROR', 'Ingest Error'), ('INGEST_RUN_ID', 'Ingest Run Number'), ('AGE_TASK', 'Age Task Result'), ('BATCH_TASK', 'Batch Sites Task Result'), ('HIDE_ARTICLES_TASK', 'Hide Articles Task Result'), ('HIDE_SITES_TASK', 'Hide Sites Task Result'), ('LAST_ARTICLE_TASK', 'Last Articles Task Result'), ('FILTER_ARTICLE_TASK', 'Filter Articles Task Result')], help_text='Category of Log', max_length=20, verbose_name='Log Type'),
        ),
    ]
