# Generated by Django 6.0.6 on 2026-07-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_logging_log_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recap',
            fields=[
            ],
            options={
                'verbose_name': 'Article Recap',
                'verbose_name_plural': 'Article Recaps',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.articles',),
        ),
    ]
