# Generated by Django 6.0.6 on 2026-07-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_recap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recap',
            options={'verbose_name': 'Recap', 'verbose_name_plural': 'Recap'},
        ),
    ]
