# Generated by Django 6.0.6 on 2026-07-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_recap_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recap',
        ),
    ]
