# Generated by Django 6.0.6 on 2026-07-04 02:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_delete_recap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=128, verbose_name='Article ID')),
                ('session', models.CharField(max_length=128, verbose_name='Session ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Vote Date')),
            ],
            options={
                'verbose_name': 'Clicks',
                'verbose_name_plural': 'Clicks',
                'db_table': 'clicks',
                'ordering': ['session'],
                'indexes': [models.Index(fields=['session', 'article'], name='vote_exists_idx')],
            },
        ),
    ]
