# Generated by Django 6.0.6 on 2026-07-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='manual_post',
            field=models.BooleanField(default=False, help_text='Post this to Bluesky, if parent site is blocked', verbose_name='Manual Post'),
        ),
        migrations.AddField(
            model_name='sites',
            name='auto_post',
            field=models.BooleanField(default=True, help_text='Can this sites articles be automatically posted to social media?', verbose_name='Auto Post'),
        ),
    ]
