# Generated by Django 6.0.6 on 2026-07-07 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_articles_manual_post_sites_auto_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adverts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of Advert, not shown', max_length=256, verbose_name='Advert Title')),
                ('message', models.CharField(help_text='Message shown in advert', max_length=256, verbose_name='Advert Message')),
                ('site_name', models.CharField(blank=True, help_text='The name of the site, shown to user', max_length=256, null=True, verbose_name='Advert Site')),
                ('site_url', models.URLField(help_text='The link the advert goes to', verbose_name='Advert URL')),
                ('start_date', models.DateField(help_text='The start date of the advert', verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='The end date of the advert', verbose_name='End Date')),
                ('concurrency', models.IntegerField(default=1, help_text='Maximum amount of times this can appear on a page', verbose_name='Concurrency')),
            ],
            options={
                'verbose_name': 'Adverts',
                'verbose_name_plural': 'Adverts',
                'db_table': 'adverts',
                'ordering': ['-end_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-created'], 'verbose_name': 'Articles', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='clicks',
            options={'ordering': ['date'], 'verbose_name': 'Clicks', 'verbose_name_plural': 'Clicks'},
        ),
        migrations.RemoveIndex(
            model_name='clicks',
            name='vote_exists_idx',
        ),
        migrations.AddField(
            model_name='clicks',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.sites'),
        ),
        migrations.AlterField(
            model_name='logic',
            name='logic_type',
            field=models.CharField(choices=[('KEYWORD', 'Keyword'), ('CATEGORY', 'Category'), ('TAG', 'Tag'), ('SITE_TYPE', 'Type'), ('AD_SIZE', 'Advert_Size')], help_text='Category of Logic', max_length=20, verbose_name='Logic Type'),
        ),
        migrations.AddField(
            model_name='adverts',
            name='advert_size',
            field=models.ForeignKey(help_text='The size of this advert', limit_choices_to={'logic_type': 'AD_SIZE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advert_size', to='website.logic', verbose_name='Advert Size'),
        ),
        migrations.RemoveField(
            model_name='clicks',
            name='session',
        ),
    ]
