# Generated by Django 6.0.6 on 2026-07-09 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_adverts_alter_articles_options_alter_clicks_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverts',
            name='advert_size',
            field=models.ForeignKey(help_text='The size of this advert', limit_choices_to={'logic_type': 'AD_SIZE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Advert_Size', to='website.logic', verbose_name='Advert Size'),
        ),
        migrations.AlterField(
            model_name='logic',
            name='logic_type',
            field=models.CharField(choices=[('KEYWORD', 'Keyword'), ('CATEGORY', 'Category'), ('TAG', 'Tag'), ('SITE_TYPE', 'Site_Type'), ('AD_SIZE', 'Advert_Size'), ('CLICK_TYPE', 'Click_Type')], help_text='Category of Logic', max_length=20, verbose_name='Logic Type'),
        ),
    ]
