# Generated by Django 6.0.6 on 2026-07-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_adverts_advert_size_alter_logic_logic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logic',
            name='logic_type',
            field=models.CharField(choices=[('KEYWORD', 'Keyword'), ('CATEGORY', 'Category'), ('TAG', 'Tag'), ('SITE_TYPE', 'Site Type'), ('AD_SIZE', 'Advert_Size'), ('CLICK_TYPE', 'Click_Type')], help_text='Category of Logic', max_length=20, verbose_name='Logic Type'),
        ),
    ]
