# Generated by Django 6.0.6 on 2026-07-28 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_adverts_advert_size_alter_logic_logic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicks',
            name='type',
            field=models.ForeignKey(help_text='The type of click registered', limit_choices_to={'logic_type': 'CLICK_TYPE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='click_type', to='website.logic', verbose_name='Click Type'),
        ),
    ]
