# Generated by Django 6.0.6 on 2026-08-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_clicks_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logic',
            options={'ordering': ['logic_type', 'value'], 'verbose_name': 'Logic', 'verbose_name_plural': 'Logic'},
        ),
        migrations.AlterUniqueTogether(
            name='logic',
            unique_together={('logic_type', 'value')},
        ),
        migrations.AlterField(
            model_name='sites',
            name='auto_post',
            field=models.BooleanField(default=True, help_text="Can this site's articles be automatically posted to social media?", verbose_name='Auto Post'),
        ),
        migrations.RemoveField(
            model_name='logic',
            name='parent',
        ),
    ]
