# Generated by Django 6.0.6 on 2026-09-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_logic_options_alter_logic_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adverts',
            index=models.Index(fields=['start_date'], name='adverts_start_d_e7e02e_idx'),
        ),
        migrations.AddIndex(
            model_name='adverts',
            index=models.Index(fields=['end_date'], name='adverts_end_dat_edb866_idx'),
        ),
        migrations.AddIndex(
            model_name='adverts',
            index=models.Index(fields=['advert_size'], name='adverts_advert__c79ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='articles',
            index=models.Index(fields=['title'], name='articles_title_53596d_idx'),
        ),
        migrations.AddIndex(
            model_name='articles',
            index=models.Index(fields=['url'], name='articles_url_426d50_idx'),
        ),
        migrations.AddIndex(
            model_name='articles',
            index=models.Index(fields=['site'], name='articles_site_id_65d78b_idx'),
        ),
        migrations.AddIndex(
            model_name='articles',
            index=models.Index(fields=['published'], name='articles_publish_8d2197_idx'),
        ),
        migrations.AddIndex(
            model_name='articles',
            index=models.Index(fields=['created'], name='articles_created_c33ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='articles',
            index=models.Index(fields=['rank'], name='articles_rank_e521b7_idx'),
        ),
        migrations.AddIndex(
            model_name='articles',
            index=models.Index(fields=['hidden'], name='articles_hidden_fd73cd_idx'),
        ),
        migrations.AddIndex(
            model_name='clicks',
            index=models.Index(fields=['type'], name='clicks_type_id_b06ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='clicks',
            index=models.Index(fields=['article'], name='clicks_article_3281e0_idx'),
        ),
        migrations.AddIndex(
            model_name='clicks',
            index=models.Index(fields=['site'], name='clicks_site_id_ef2db3_idx'),
        ),
        migrations.AddIndex(
            model_name='clicks',
            index=models.Index(fields=['date'], name='clicks_date_cea6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='logging',
            index=models.Index(fields=['log_type'], name='logging_log_typ_b488dc_idx'),
        ),
        migrations.AddIndex(
            model_name='logging',
            index=models.Index(fields=['created'], name='logging_created_78ef54_idx'),
        ),
        migrations.AddIndex(
            model_name='logic',
            index=models.Index(fields=['logic_type'], name='logic_logic_t_c263f1_idx'),
        ),
        migrations.AddIndex(
            model_name='logic',
            index=models.Index(fields=['value'], name='logic_value_9bbe8c_idx'),
        ),
        migrations.AddIndex(
            model_name='sites',
            index=models.Index(fields=['name'], name='sites_name_4af64c_idx'),
        ),
        migrations.AddIndex(
            model_name='sites',
            index=models.Index(fields=['url'], name='sites_url_42771d_idx'),
        ),
        migrations.AddIndex(
            model_name='sites',
            index=models.Index(fields=['hidden'], name='sites_hidden_535e46_idx'),
        ),
        migrations.AddIndex(
            model_name='sites',
            index=models.Index(fields=['category'], name='sites_categor_2d4dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='sites',
            index=models.Index(fields=['site_type'], name='sites_site_ty_fbb6a0_idx'),
        ),
    ]
