# Generated by Django 6.0.6 on 2026-09-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_adverts_adverts_start_d_e7e02e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='article_count',
            field=models.IntegerField(default=0, help_text='Count of articles under this site', verbose_name='Article Count'),
        ),
    ]
