# Generated by Django 6.0.6 on 2026-09-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_sites_article_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logging',
            options={'ordering': ['-created'], 'verbose_name': 'Logging', 'verbose_name_plural': 'Logging'},
        ),
        migrations.AlterField(
            model_name='logging',
            name='log_type',
            field=models.CharField(choices=[('INGEST_COMPLETE', 'Ingest Complete'), ('INGEST_ERROR', 'Ingest Error'), ('INGEST_RUN_ID', 'Ingest Run Number'), ('AGE_TASK', 'Age Task Result'), ('BATCH_TASK', 'Batch Sites Task Result'), ('HIDE_ARTICLES_TASK', 'Hide Articles Task Result'), ('HIDE_SITES_TASK', 'Hide Sites Task Result'), ('LAST_ARTICLE_TASK', 'Last Articles Task Result'), ('FILTER_ARTICLE_TASK', 'Filter Articles Task Result'), ('COUNT_ARTICLES', 'Articles Counted')], help_text='Category of Log', max_length=20, verbose_name='Log Type'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='bluesky',
            field=models.CharField(help_text='Bluesky Handle', max_length=256, verbose_name='Bluesky'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='modifier',
            field=models.FloatField(blank=True, default=2, help_text='Rank Modifier', verbose_name='Modifier Value'),
        ),
    ]
