# Generated by Django 6.0.6 on 2026-10-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_logging_options_alter_logging_log_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='bluesky',
            field=models.CharField(blank=True, help_text='Bluesky Handle', max_length=256, verbose_name='Bluesky'),
        ),
    ]
