# Generated by Django 6.0.6 on 2026-10-07 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_sites_bluesky'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverts',
            name='advert_size',
            field=models.ForeignKey(help_text='The size of this advert', limit_choices_to={'logic_type': 'AD_SIZE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advert_size', to='website.logic', verbose_name='Advert Size'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.sites'),
        ),
        migrations.AlterField(
            model_name='clicks',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='website.sites'),
        ),
        migrations.AlterField(
            model_name='clicks',
            name='type',
            field=models.ForeignKey(help_text='The type of click registered', limit_choices_to={'logic_type': 'CLICK_TYPE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='click_type', to='website.logic', verbose_name='Click Type'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='category',
            field=models.ForeignKey(help_text='Select a category for this site', limit_choices_to={'logic_type': 'CATEGORY'}, on_delete=django.db.models.deletion.PROTECT, related_name='site_category', to='website.logic', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='site_type',
            field=models.ForeignKey(help_text='Select a type for this site', limit_choices_to={'logic_type': 'SITE_TYPE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_type', to='website.logic', verbose_name='Type'),
        ),
    ]
