# Generated by Django 6.0.6 on 2026-10-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_adverts_advert_size_alter_articles_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='recap',
            field=models.BooleanField(default=True, help_text="Include this site's articles in the weekly newsletter recap?", verbose_name='Include in Recap'),
        ),
    ]
