# Generated by Django 6.0.6 on 2026-10-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_adverts_size_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicks',
            name='clicks',
            field=models.FloatField(default=0, help_text='Count of link clicks', verbose_name='Click Count'),
        ),
    ]
