# Generated by Django 6.0.6 on 2026-10-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_clicks_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverts',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image shown on the advert card', upload_to='adverts/', verbose_name='Advert Image'),
        ),
    ]
