# Generated by Django 6.0.6 on 2026-10-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_adverts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverts',
            name='clicks',
            field=models.FloatField(default=0, help_text='Count of link clicks', verbose_name='Click Count'),
        ),
    ]
