# Generated by Django 6.0.6 on 2026-10-08 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_adverts_clicks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clicks',
            name='clicks',
        ),
    ]
