# Generated by Django 6.0.6 on 2026-10-08 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_remove_clicks_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='log_type',
            field=models.CharField(choices=[('INGEST_COMPLETE', 'Ingest Complete'), ('INGEST_ERROR', 'Ingest Error'), ('INGEST_RUN_ID', 'Ingest Run Number'), ('AGE_TASK', 'Age Task Result'), ('BATCH_TASK', 'Batch Sites Task Result'), ('HIDE_ARTICLES_TASK', 'Hide Articles Task Result'), ('HIDE_SITES_TASK', 'Hide Sites Task Result'), ('LAST_ARTICLE_TASK', 'Last Articles Task Result'), ('FILTER_ARTICLE_TASK', 'Filter Articles Task Result'), ('COUNT_ARTICLES', 'Articles Counted'), ('ANALYTICS_TASK', 'Analytics Task Result')], help_text='Category of Log', max_length=20, verbose_name='Log Type'),
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='The id of the article or advert, depending on the type', verbose_name='Object ID')),
                ('month', models.DateField(help_text='Always the first day of the month, e.g. 2026-09-01', verbose_name='Month')),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Counted clicks in this month', verbose_name='Click Count')),
                ('site', models.ForeignKey(blank=True, help_text="The article's site (blank for adverts)", null=True, on_delete=django.db.models.deletion.PROTECT, to='website.sites')),
                ('type', models.ForeignKey(help_text='Article or Advert', limit_choices_to={'logic_type': 'CLICK_TYPE'}, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_type', to='website.logic', verbose_name='Click Type')),
            ],
            options={
                'verbose_name': 'Analytics',
                'verbose_name_plural': 'Analytics',
                'db_table': 'analytics',
                'ordering': ['-month', 'type', 'object_id'],
                'indexes': [models.Index(fields=['type', 'object_id', 'month'], name='analytics_type_id_9a9455_idx'), models.Index(fields=['month'], name='analytics_month_03bfd5_idx'), models.Index(fields=['site', 'month'], name='analytics_site_id_82bd4f_idx')],
                'constraints': [models.UniqueConstraint(fields=('type', 'object_id', 'month'), name='unique_analytics_month')],
            },
        ),
    ]
